package org.example.Image.pojo.colonoscope;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.IID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private Integer iid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.ImageName
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String imagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.ImagePath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String imagepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.MaskPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String maskpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.BoundingBoxPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String boundingboxpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..image.UploadDate
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private Date uploaddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.IID
     *
     * @return the value of colonoscope..image.IID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.IID
     *
     * @param iid the value for colonoscope..image.IID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.UID
     *
     * @return the value of colonoscope..image.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.UID
     *
     * @param uid the value for colonoscope..image.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.ImageName
     *
     * @return the value of colonoscope..image.ImageName
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.ImageName
     *
     * @param imagename the value for colonoscope..image.ImageName
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setImagename(String imagename) {
        this.imagename = imagename == null ? null : imagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.ImagePath
     *
     * @return the value of colonoscope..image.ImagePath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.ImagePath
     *
     * @param imagepath the value for colonoscope..image.ImagePath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.MaskPath
     *
     * @return the value of colonoscope..image.MaskPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getMaskpath() {
        return maskpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.MaskPath
     *
     * @param maskpath the value for colonoscope..image.MaskPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setMaskpath(String maskpath) {
        this.maskpath = maskpath == null ? null : maskpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.BoundingBoxPath
     *
     * @return the value of colonoscope..image.BoundingBoxPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getBoundingboxpath() {
        return boundingboxpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.BoundingBoxPath
     *
     * @param boundingboxpath the value for colonoscope..image.BoundingBoxPath
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setBoundingboxpath(String boundingboxpath) {
        this.boundingboxpath = boundingboxpath == null ? null : boundingboxpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..image.UploadDate
     *
     * @return the value of colonoscope..image.UploadDate
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public Date getUploaddate() {
        return uploaddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..image.UploadDate
     *
     * @param uploaddate the value for colonoscope..image.UploadDate
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setUploaddate(Date uploaddate) {
        this.uploaddate = uploaddate;
    }
}