package org.example.Image.pojo.colonoscope;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Username
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Password
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Telephone
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.WeChat
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Email
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Province
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.City
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.District
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column colonoscope..user.Street
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    private String street;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.UID
     *
     * @return the value of colonoscope..user.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.UID
     *
     * @param uid the value for colonoscope..user.UID
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Username
     *
     * @return the value of colonoscope..user.Username
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Username
     *
     * @param username the value for colonoscope..user.Username
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Password
     *
     * @return the value of colonoscope..user.Password
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Password
     *
     * @param password the value for colonoscope..user.Password
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Telephone
     *
     * @return the value of colonoscope..user.Telephone
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Telephone
     *
     * @param telephone the value for colonoscope..user.Telephone
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.WeChat
     *
     * @return the value of colonoscope..user.WeChat
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.WeChat
     *
     * @param wechat the value for colonoscope..user.WeChat
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Email
     *
     * @return the value of colonoscope..user.Email
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Email
     *
     * @param email the value for colonoscope..user.Email
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Province
     *
     * @return the value of colonoscope..user.Province
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Province
     *
     * @param province the value for colonoscope..user.Province
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.City
     *
     * @return the value of colonoscope..user.City
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.City
     *
     * @param city the value for colonoscope..user.City
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.District
     *
     * @return the value of colonoscope..user.District
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.District
     *
     * @param district the value for colonoscope..user.District
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column colonoscope..user.Street
     *
     * @return the value of colonoscope..user.Street
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column colonoscope..user.Street
     *
     * @param street the value for colonoscope..user.Street
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }
}