server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colonoscope?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '001124'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: org.example.Image.pojo.colonoscope
  mapper-locations: classpath:mapper/colonoscope/*.xml

# MyBatis Generator 插件配置
mybatis-generator:
  configuration-file: src/main/resources/generatorConfig.xml

python:
  interpreter: 'E:\PyCharm2022.3\Workplace_1\DeepLearning_base\venv\Scripts\python.exe'

image-savepath: 'E:\IDEA2018\IDEAworkplace3\colonoscope\public\images'