package org.example.Image.mapper.colonoscope;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.Image.pojo.colonoscope.Image;
import org.example.Image.pojo.colonoscope.ImageExample;
@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    long countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    Image selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByExampleSelective(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByExample(@Param("record") Image record, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..image
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByPrimaryKey(Image record);
}