package org.example.Image.mapper.colonoscope;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.example.Image.pojo.colonoscope.User;
import org.example.Image.pojo.colonoscope.UserExample;
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */

    User selectByUserName(String username);
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table colonoscope..user
     *
     * @mbg.generated Thu Apr 13 19:14:54 CST 2023
     */
    int updateByPrimaryKey(User record);
}